// Kid-friendly words for each letter with corresponding emoji
export const alphabetData = {
  A: { word: 'Apple', emoji: '🍎' },
  B: { word: 'Ball', emoji: '⚽' },
  C: { word: 'Cat', emoji: '🐱' },
  D: { word: 'Dog', emoji: '🐕' },
  E: { word: 'Elephant', emoji: '🐘' },
  F: { word: 'Fish', emoji: '🐠' },
  G: { word: 'Giraffe', emoji: '🦒' },
  H: { word: 'Horse', emoji: '🐴' },
  I: { word: 'Ice Cream', emoji: '🍦' },
  J: { word: 'Jellyfish', emoji: '🪼' },
  K: { word: 'Kite', emoji: '🪁' },
  L: { word: 'Lion', emoji: '🦁' },
  M: { word: 'Monkey', emoji: '🐵' },
  N: { word: 'Nest', emoji: '🪹' },
  O: { word: 'Orange', emoji: '🍊' },
  P: { word: 'Penguin', emoji: '🐧' },
  Q: { word: 'Queen', emoji: '👸' },
  R: { word: 'Rainbow', emoji: '🌈' },
  S: { word: 'Sun', emoji: '☀️' },
  T: { word: 'Tiger', emoji: '🐯' },
  U: { word: 'Umbrella', emoji: '☂️' },
  V: { word: 'Violin', emoji: '🎻' },
  W: { word: 'Whale', emoji: '🐋' },
  X: { word: 'Xylophone', emoji: '🎵' },
  Y: { word: 'Yo-yo', emoji: '🪀' },
  Z: { word: 'Zebra', emoji: '🦓' },
}

